### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by ibiBgOR**
For the routing I had to refactor quite a lot. (fixes issue #9)

This was the case because some components just did to much work. With the refactored code I tried to split the concerns and each component should only do work it was designed for..

New features I added while refactor:
* routing (pretty obvious)
* Saving with ctrl+s
* Notification on unsaved changes if navigate away from a note

Features I could not copy:
* "Reset" of a notes content (replaceable with navigating away from the note and discard changes)

With all the changes done in the meantime I guess this is WIP.

### CODE REVIEW

**Comment by ibiBgOR** [comment]
For the saving part issue #14 is included... I only send one note to the server... But one could do the same on loading all notes for a notebook. Currently all notes (including content) will get loaded.

**Comment by n1try** [comment]
Thanks for this one, I really appreciate your effort!

I did not look at the code in detail, yet, but at least there are a few visual issues, as (professionally) depicted in the screen shot below.

mininote

- [ ] There is no save button
- [ ] The top input bar should show the current notebook's name
- [ ] Buttons should be either green or grey, but not blue
- [ ] Some other, obvious visual issues
- [ ] When trying to open a non-existing notebook, the user should be shown an error alert message to have some feedback
- [ ] Settings button (and password-change modal) should not be available on front page when no notebook is opened, obviously

Did you merge the latest `master` into your branch? Maybe that will already resolve a few of these issues.

**Comment by ibiBgOR** [comment]
Hey there.
Most of the issues appeared after merging the current master to my local branch.. I guess I didn't do it correctly.
I will try to resolve all issues ASAP, but at the moment I haven't that much time.

**Comment by ibiBgOR** [comment]
I found some time today:
I think there is no "save button" nessecary anymore. ctrl+s will work as fine. Also if the user navigates away from the note and still got some unsaved changes, the programm asks if the user wants to save them first. (Also including the save button into the controlbar is a break against the architecture. the controlbar should not know what note is currently open IMHO)

The last issue is not reproducible to me.

**Comment by n1try** [comment]
Can't reproduce the last one neither, anymore. Forget about it for now.

Concerning save button: I agree that it is not completely necessary anymore, but for the sake of a better user experience I would really like to still have it there. Same for the "Open" button when opening a new notebook.

**Comment by n1try** [comment]
Thanks again!

However, I am still not totally happy with that, sorry :/

1. After having created a new notebook, the new notebook's name is in the input field in the top. Why? It is not open. The input field should still be empty, just as before having created the notebook.
2. Give the `.btn-editor` a `position: absolute` please
3. This does not look quite right. And I'd still prefer a `Save` and a `Open` button.
image

**Comment by ibiBgOR** [comment]
I added the open button and the save button.
But the save button has a new location in the editor and preview boxed. There the user knows exactly, that only this note will be saved, not the whole notebook (which is now technically correct).

But sadly again I cannot reproduce your first issue, that the notebook name is prefilled.

**Comment by ibiBgOR** [comment]
Still got another issue. After changing the password of a notebook, I cannot work with the notes, because the password is not set for all views... Looking right into that.

**Comment by n1try** [comment]
Thanks again! I am so sorry, but there are further bugs that need to be fixed. I really appreciate your effort and I know how annoying those change requests are, but I do not want to merge any bugs into master. Take a look at [this screen recording](https://drive.google.com/open?id=1lBMuTWvjb76W9gZmJ_a5Y8-YSvnUWuxm) (don't care about the weird colors, it's a recording issue).

* [ ] [0:00] Input bar, "Please create..."-text and button should all be horizontally centered (currently, input bar is shifted to the right)
* [ ] [0:07] "X" button should clear the input field, "Open" button should take the user to the password prompt
* [ ] [0:40] Everything had already been saved. There should not be another confirm dialog
* [ ] [0:54] Same as above
* [ ] [1:00] Now that changes are persisted immediately, the user should be able to confirm the delete operation. Otherwise their entire note might be accidentally gone with a single click.
* [ ] [1:14] Does not look quite right

**Pull request closed without merging**
