### PR TITLE
Adding feature to rename notebooks

### PR DESCRIPTION
**Pull request by anurag-rai**
Partly solves #1

### CODE REVIEW

**Comment by n1try** [comment]
Thanks. But the password input in the settings dialog should not appear to be empty, when it isn't. This is confusing for the user.

**Comment by n1try** [comment]
Do you plan to implement the change requests?

**Comment by n1try** [comment]
Couldn't the password input just show (maybe hidden by dots) the current password and the name input the current name? I guess than it would be clearer. Currently, the confusing thing is that the password input is empty.

**Comment by anurag-rai** [comment]
Yes, we can do that. Both fields will by default have the current notebook name and password.

**Comment by n1try** [comment]
Any news on this, @anurag-rai ?

**Comment by n1try** [comment]
Dude?

**Comment by anurag-rai** [comment]
Hey, I'm so sorry @n1try ... I was down with sickness and hospitalized for over a fortnight. I'm back now. Will update on this through this coming weekend. I hope this is not a blocker.

**Pull request closed without merging**
